export interface IdataFilter {
  area: string;
  section: string[];
  host: string[][];
  printer: string[][];
}

/* *************************** */
export const dataFilter: IdataFilter[] = [
  {
    area: 'Planta Principal',
    section: [
      'Bodega Hilaza',
      'Calderas',
      'Contenedor',
      'Consultorio Médico',
      'Hilatura',
      'Laboratorio Textil',
      'Reciclaje Industrial',
      'Revisión de Hilos',
      'Revisión de Terminado',
      'Tecnologías de la Información',
      'Tejido Plano',
      'Texturizado',
      'Tintas Mesanine',
    ],
    host: [
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
    ],
    printer: [
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
    ],
  },
  {
    area: 'PDV Bogotá',
    section: [
      '7 De Agosto',
      '150',
      'Alamos',
      'AV Boyacá',
      'Cajicá',
      'Cedritos',
      'Centro Nariño',
      'Ricaurte',
      'Soacha',
      'Suba',
      'Toberín',
    ],
    host: [
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
    ],
    printer: [
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
    ],
  },
  {
    area: 'PDV Nacionales',
    section: [
      'Barranquilla',
      'Bucaramanga',
      'Cali',
      'Cúcuta',
      'Ibagué',
      'Medellín',
      'Neiva',
      'Santa Marta',
      'Villavicencio',
    ],
    host: [
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
    ],
    printer: [
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
    ],
  },
  {
    area: 'PDV Internacionales',
    section: ['Costa Rica', 'Venezuela'],
    host: [
      ['Access Point', 'Data Center', 'Impresoras'],
      ['Access Point', 'Data Center', 'Impresoras'],
    ],
    printer: [
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
      [
        'CL4NX SATO',
        'EPSON FS-2190',
        'EPSON FS 2190II',
        'EPSON FS-850',
        'EPSON TMU 220',
        'KYOCERA',
      ],
    ],
  },
];
